"""Add tts_model to Project

Revision ID: adab2af26c6f
Revises: 227ba3c22a92
Create Date: 2026-06-15 10:49:55.230501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'adab2af26c6f'
down_revision: Union[str, Sequence[str], None] = '227ba3c22a92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('tts_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='gemini-2.5-flash-preview-tts'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'tts_model')
    # ### end Alembic commands ###
